module.exports = '\
    PRAGMA FOREIGN_KEYS = ON;\
    CREATE TABLE tblUser (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, account TEXT Not Null UNIQUE, password TEXT Not Null, fname TEXT Not Null, lname TEXT Not Null, pcode TEXT Not Null UNIQUE, workunit TEXT Not Null, sysadmin BOOLEAN Not Null, github TEXT, telegram TEXT, attribute TEXT);\
    CREATE TABLE tblReportClass (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, caption TEXT Not Null UNIQUE, duration TEXT, user_owner INTEGER REFERENCES tblUser (id), caption_pitypes TEXT, weight_pitypes TEXT, attribute TEXT);\
    CREATE TABLE tblPIType_1 (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, caption TEXT Not Null UNIQUE, code TEXT Not Null, attribute TEXT);\
    CREATE TABLE tblPIType_2 (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, caption TEXT Not Null UNIQUE, code TEXT Not Null, pitype_1_id REFERENCES tblPIType_1 (id), attribute TEXT);\
    CREATE TABLE tblPIType_3 (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, caption TEXT Not Null UNIQUE, code TEXT Not Null, pitype_2_id REFERENCES tblPIType_2 (id), attribute TEXT);\
    CREATE TABLE tblVariableDef (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, unit TEXT Not Null, caption TEXT Not Null UNIQUE, code TEXT Not Null UNIQUE, user_provider INTEGER REFERENCES tblUser (id), user_owner INTEGER REFERENCES tblUser (id), user_reviewer INTEGER REFERENCES tblUser (id), attribute TEXT);\
    CREATE TABLE tblJunctionClass (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, reportclass_id INTEGER Not Null REFERENCES tblReportClass (id), variabledef_id INTEGER Not Null REFERENCES tblVariableDef (id), pitype_3_id INTEGER REFERENCES tblPIType_3 (id), weight DOUBLE);\
    CREATE TABLE tblReport (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, caption TEXT Not Null UNIQUE, time_limit INTEGER Not Null, user_owner INTEGER Not Null REFERENCES tblUser (id), user_creator INTEGER Not Null REFERENCES tblUser (id), ip_user TEXT Not Null, time_create INTEGER Not Null, pathfile TEXT, time_latestissue INTEGER, attribute TEXT);\
    CREATE TABLE tblPI (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, unit TEXT Not Null, caption TEXT Not Null UNIQUE, code TEXT Not Null UNIQUE, user_provider INTEGER Not Null REFERENCES tblUser (id), user_owner INTEGER Not Null REFERENCES tblUser (id), user_reviewer INTEGER Not Null REFERENCES tblUser (id), attribute TEXT);\
    CREATE TABLE tblJunction (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, report_id INTEGER Not Null REFERENCES tblReport (id), pi_id INTEGER Not Null REFERENCES tblPI (id), weight TEXT);\
    CREATE TABLE tblAttachment (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, report_id INTEGER Not Null REFERENCES tblReport (id), pathfile TEXT Not Null, user_attach INTEGER Not Null REFERENCES tblUser (id), ip_user TEXT Not Null, time_attach INTEGER Not Null, attribute TEXT);\
    CREATE TABLE tblPIValue (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, pi_id INTEGER REFERENCES tblPI (id), value DOUBLE Not Null, time_update INTEGER Not Null, user_update INTEGER Not Null REFERENCES tblUser (id), ip_user TEXT Not Null, attribute TEXT);\
    CREATE TABLE tblPITarget (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, pi_id INTEGER REFERENCES tblPI (id), value DOUBLE Not Null, time_target INTEGER Not Null, time_update INTEGER Not Null, user_update INTEGER Not Null REFERENCES tblUser (id), ip_user TEXT Not Null, attribute TEXT);\
    CREATE TABLE tblMessage (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, textmessage TEXT Not Null, time_message INTEGER Not Null, ip_sender TEXT Not Null, user_sender INTEGER REFERENCES tblUser (id), user_reciever INTEGER Not Null REFERENCES tblUser (id), pi_id INTEGER REFERENCES tblPI (id), teme_read INTEGER, attribute TEXT);';
