exports.ddl = '\
    CREATE TABLE tblUser (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, fname TEXT Not Null, lname TEXT Not Null, pcode TEXT Not Null, unit TEXT Not Null, tel TEXT);\
    CREATE TABLE tblReportClass (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, caption TEXT Not Null, dayduration INTEGER, userowner INTEGER REFERENCES tblUser (id));\
    CREATE TABLE tblReport (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, reportclass INTEGER Not Null REFERENCES tblReportClass (id), caption TEXT Not Null, timelimit INTEGER Not Null, userowner INTEGER Not Null REFERENCES tblUser (id), usercreator INTEGER Not Null REFERENCES tblUser (id), ipcreator TEXT Not Null, timecreate INTEGER Not Null, pathfile TEXT, timelatestissue INTEGER);\
    CREATE TABLE tblAttachment (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, reportreference INTEGER Not Null REFERENCES tblReport (id), path TEXT Not Null, userattach INTEGER Not Null REFERENCES tblUser (id), userip TEXT Not Null, timeattach INTEGER Not Null, desc TEXT);\
    CREATE TABLE tblPIType_1 (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, caption TEXT Not Null);\
    CREATE TABLE tblPIType_2 (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, caption TEXT Not Null, type REFERENCES tblPIType_1 (id));\
    CREATE TABLE tblPIType_3 (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, caption TEXT Not Null, type REFERENCES tblPIType_2 (id));\
    CREATE TABLE tblPIClass (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, reportclass INTEGER Not Null REFERENCES tblReportClass (id), unit TEXT Not Null, caption TEXT Not Null, type_1 INTEGER REFERENCES tblPIType_1 (id), type_2 INTEGER REFERENCES tblPIType_2 (id), type_3 INTEGER REFERENCES tblPIType_3 (id), userprovider INTEGER Not Null REFERENCES tblUser (id), userowner INTEGER Not Null REFERENCES tblUser (id), userreviewer INTEGER Not Null REFERENCES tblUser (id));\
    CREATE TABLE tblPI (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, PIclass INTEGER Not Null REFERENCES tblPIClass (id), unit TEXT Not Null, caption TEXT Not Null, userprovider INTEGER Not Null REFERENCES tblUser (id), userowner INTEGER Not Null REFERENCES tblUser (id), userreviewer INTEGER Not Null REFERENCES tblUser (id));\
    CREATE TABLE tblPIvalue (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, pireference INTEGER REFERENCES tblPI (id), value DOUBLE Not Null, updatetime INTEGER Not Null, userupdate INTEGER Not Null REFERENCES tblUser (id), ipupdate TEXT Not Null);\
    CREATE TABLE tblPItarget (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, pireference INTEGER REFERENCES tblPI (id), value DOUBLE Not Null, timeat INTEGER Not Null, updatetime INTEGER Not Null, userupdate INTEGER Not Null REFERENCES tblUser (id), ipupdate TEXT Not Null);\
    CREATE TABLE tblMessage (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE, textmessage TEXT Not Null, timemessage INTEGER Not Null, ipsender TEXT Not Null, usersender INTEGER Not Null REFERENCES tblUser (id), userreciever INTEGER Not Null REFERENCES tblUser (id), pireference INTEGER REFERENCES tblPI (id), isread BOOLEAN Not Null);';
