const fa = {
  'View Details': 'بررسی ...',
  'New Comments!': 'پیام جدید',
  'New Tasks!': 'دستور جدید',
  'New Orders!': 'درخواست جدید',
  'Support Tickets!': 'گزارش جدید',
  'title': 'سیستم تحلیل گزارشات مدیریت',
  'report title': 'عنوان گزارش',
  'time left': 'زمان باقی مانده',
  'open report': 'گزارش باز میباشد',
  'PI': 'شاخص',
  'PI registered': 'شاخص های گزارش',
  'PI entered': 'دستاورد های ثبت شده',
  'PI real': 'دستاورد',
  'from': 'از',
  'report progress': 'پیشرفت گزارش',
  'user progress': 'وضعیت کاربر',
  'config': 'تنظیمات',
  'Edit Time': 'زمان ویرایش',
  'Upper Limit': 'حد بالا',
  'Lower Limit': 'حد پایین',
  'Unit': 'واحد',
  'Attach': 'پیوست',
  'Dashboard': 'داشبورد',
  'Statistics Overview': 'آمار کلی',
  'Reports Archive': 'بایگانی گزارشات',
  'Design': 'طراحی',
  'Categories': 'طبقه بندی شاخص ها',
  'PIs': 'شاخص ها',
  'Reports': 'گزارشات',
  'Users': 'کاربران',
  'User Config': 'تنظیمات کاربران',
  'Inbox': 'صندوق دریافتی',
  'Log Out': 'خروج',
  'Settings': 'تنظیمات',
  'Sample User': 'حامد روحانی',
  'Alert Name': 'پیام',
  'Alert Default': 'عادی',
  'Alert Primary': 'جدی',
  'Alert Success': 'موفق',
  'Alert Info': 'اطلاع',
  'Alert Warning': 'هشدار',
  'Alert Danger': 'اخطار',
  'View All': 'نمایش همه',
  'result 1': 'یک گزارش',
  'result 2': 'یک شاخص',
  'result 3': 'گزارش',
  'result 4': 'کاربر',
  'result 5': 'پیام'
};
module.exports = fa;
